name: Telegram UserBot Forwarder

on:
  schedule:
    - cron: '*/15 * * * *'  # Каждые 15 минут
  workflow_dispatch:  # Ручной запуск

jobs:
  forward-messages:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run UserBot
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        PHONE: ${{ secrets.PHONE }}
        STRING_SESSION: ${{ secrets.STRING_SESSION }}
        SOURCE_CHATS: ${{ secrets.SOURCE_CHATS }}
        TARGET_CHAT: ${{ secrets.TARGET_CHAT }}
      run: |
        python userbot.py
